### ISSUE TITLE
Reminder to start mobster if certain applications have focus

### ISSUE THREAD

**Issue by davelowelarsson** [sveriges-utbildningsradio/ur-mobster#31]
for example if VS Code, Iterm or other applications have focus but the mobster application is open but not started, remind the user to start mobster

**Comment by AElmoznino** [comment]
Seems like you can't detect what other app is focused:
https://stackoverflow.com/questions/39930279/how-can-you-get-information-about-other-apps-running-or-in-focus

However it's possible to listen to the blur event.

**Comment by AElmoznino** [comment]
Closing - [this commit](https://github.com/sveriges-utbildningsradio/ur-mobster/commit/9e648a3754f1e5b3153581befb618a6076143058) makes it pop up every minute when switching app (if the timer isn't running).
